apiVersion: apps/v1
kind: Deployment
metadata:
  name: testbuggy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testbuggy
  template:
    metadata:
      labels:
        app: testbuggy
    spec:
      containers:
      - name: testbuggy
        image: 554088301769.dkr.ecr.us-east-1.amazonaws.com/ham
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: testbuggy
    k8s-app: testbuggy
  name: testbuggy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: testbuggy
